<?php

/*
 * WP Assets File - generated by node module @wordpress/dependency-extraction-webpack-plugin.
 * used for auto-versioning with file hashes.
 * */
$asset_file = include( get_stylesheet_directory() . '/js/main.asset.php' );

if (!function_exists("skke_log")) {
  function skke_log($obj) {
    $o = "";
    ob_start();
    var_dump($obj);
    $o = ob_get_contents();
    ob_end_clean();
    error_log($o);
  } 
}

function theme_scripts() {
  global $asset_file;

  // wp_enqueue_script( 'flexslider' );    
  // wp_enqueue_script( 'jquery-ui-slider' );

  $dependencies = $asset_file['dependencies'];

  // $dependencies[] = 'flexslider';
  // $dependencies[] = 'jquery-ui-slider';
  // $dependencies[] = 'wp-i18n';

  wp_enqueue_script('freunde-auf-pfoten-mainjs', get_stylesheet_directory_uri() . '/js/main.js', $dependencies, $asset_file['version'], true);

  wp_localize_script('freunde-auf-pfoten-mainjs', 'wp_js_data',
    [
      'site_url' => esc_url(home_url()),
      'root' => esc_url_raw( rest_url() ),
      'theme_js_dir' => get_stylesheet_directory_uri() . '/js/',
      'nonce' => wp_create_nonce('wp_rest')
    ]
  );
}
add_action('wp_enqueue_scripts', 'theme_scripts');

function theme_styles() {
  global $asset_file;

  wp_enqueue_style('freunde-auf-pfoten-maincss', get_stylesheet_directory_uri() . '/css/main.css', [], $asset_file['version']);
}
add_action('wp_enqueue_scripts', 'theme_styles');

// function remheadlink() {
//   remove_action('wp_head', 'rsd_link');
//   remove_action('wp_head', 'wlwmanifest_link');
// }
// add_action('init', 'remheadlink');

function register_site_menu() {
  register_nav_menu( 'primary', 'Primary Menu' );
  register_nav_menu( 'footer-menu', 'Footer Menu' );
}
add_action( 'after_setup_theme', 'register_site_menu' );

// load_theme_textdomain( 'k0b', get_template_directory() . '/languages' );

// setlocale(LC_TIME, "bs_BA.UTF8");
// setlocale(LC_TIME, "de_DE.UTF8");

add_theme_support( 'post-thumbnails' );
add_theme_support( 'title-tag' );
add_theme_support( 'custom-logo' );

// This does not seam to work..
// remove_theme_support( 'block-templates' );

function mytheme_setup_theme() {
  add_theme_support( 'wp-block-styles' );
  // add_theme_support( 'align-wide' );
  add_theme_support( 'disable-custom-font-sizes' );
  add_theme_support( 'disable-custom-colors' );
  add_theme_support( 'disable-custom-gradients' );
  add_theme_support( 'responsive-embeds' );
  add_theme_support( 'custom-spacing' );
  add_theme_support( 'appearance-tools' );
  add_theme_support( 'border' );
  add_theme_support( 'link-color' );
  add_theme_support( 'block-template-parts' );
  add_theme_support( 'html5', array( 'comment-list', 'comment-form', 'search-form', 'gallery', 'caption', 'style', 'script' ) );

  add_image_size( 'my_icon', 64 );
  add_image_size( 'my_s_thumb', 100 );
  add_image_size( 'my_thumb', 200 );
  add_image_size( 'my_s_mid', 400 );
  add_image_size( 'my_mid', 600 );
  add_image_size( 'my_large', 1024 );
  add_image_size( 'my_xlarge', 1200 );
  add_image_size( 'my_2x_mid', 1200 );
  add_image_size( 'my_2x_large', 2048 );
  add_image_size( 'my_2x_xlarge', 2400 );
  add_image_size( 'og_image', 1200, 630, true );
}

add_action( 'after_setup_theme', 'mytheme_setup_theme' );

/**
 * Disable search.
 */
function disable_search($query, $error = true)
{
    if (is_search() && !is_admin()) {
        $query->is_search = false;
        $query->query_vars['s'] = false;
        $query->query['s'] = false;

        if ($error == true) $query->is_404 = true;
    }
}

add_action('parse_query', 'disable_search');
add_filter('get_search_form', function(){ return null; });

/**
 * Make sure we areusing lasy loading for images.
 */
add_filter( 'wp_get_attachment_image_attributes', function( $attr, $attachment, $size ) {

  if ( ! isset($attr['loading']) ) {
    $attr['loading'] = 'lazy';
  }

	return $attr;
}, 10, 3 );

/**
 * Do not load embeded stuff without JS code (asks for permission).
 */
add_filter( 'render_block', function($block_content, $parsed_block, $that) {

  if ( $parsed_block["blockName"] && strpos( $parsed_block["blockName"], 'embed' ) !== false ) {
    return str_replace(' src="', ' data-ks-embed-orig-src="', $block_content);
  }

  return $block_content;
}, 99, 3);

// add_filter( 'render_block_core/image', function($block_content, $parsed_block, $that) {
//   skke_log($block_content);

//   return $block_content;
// }, 999, 3);

/**
 * Do not load images without JS code:
 */
add_filter( 'wp_content_img_tag', function($filtered_image, $context, $attachment_id) {
  if ($context && $context === "the_content") {
    $r = str_replace(' src="', ' data-sk-src="', $filtered_image);
    return str_replace(' srcset="', ' data-sk-srcset="', $r);
  }

  return $filtered_image;
}, 99, 3);

add_filter( 'excerpt_length', function() { return 30; }, 999 );

/**
 * Helper Function for creating srcset attribute for img HTML tag.
 * 
 */
function sk_get_srcset($at_id) {
  $r = '';
  $meta_data = wp_get_attachment_metadata($at_id);
  $up_data = wp_upload_dir();
  $up_path = $up_data["baseurl"];
  $img_url = $up_path . '/' . $meta_data["file"];
  $img_dir = dirname($img_url);

  if (is_array($meta_data["sizes"])) {
    foreach ($meta_data["sizes"] as $size) {
      if (! empty($r)) {
        $r .= ', ';
      }

      $r .= $img_dir . '/' . $size["file"] . ' ' . $size["width"] . 'w';
    }
  }
  return $r;
}

/*
 * Do not fetch avatars from the net.
 * */
add_filter( 'get_avatar_url', function($url) {
  return get_stylesheet_directory_uri() . '/img/avatar.jpg';
}, 999, 1);

/**
 * Creates HTML head meta description tag.
 */
function skke_get_meta_desc() {
  global $post;
  $_queried_object = get_queried_object();

  $r = get_bloginfo( 'description' );

  if ( $_queried_object && is_archive() && ! empty($_queried_object->description) ) {
    $r =  $_queried_object->description;
  }
  else if ( $post && is_singular() ) {
    $r = get_the_excerpt( $post );
  }

  return $r;
}

/**
 * Creates SEO meta tags for the HTML head.
 */
function skke_get_seo_tags() {
  global $post;
  $_queried_object = get_queried_object();

  $a = [];

  $a["og:locale"] = get_locale();
  $a["og:description"] = skke_get_meta_desc();

  if ( is_singular() ) {
    $a["og:type"] = "article";
  } else {
    $a["og:type"] =  "website";
  }

  $img = get_template_directory_uri() . '/img/freunde.png';

  if (is_archive()) {
    $archive_pic_id = get_field('kategorie_bild', $_queried_object->taxonomy . '_' . $_queried_object->term_id);
    if ($archive_pic_id) {
      $a_img_src = wp_get_attachment_image_src( $archive_pic_id, 'og_image');
      if (is_array($a_img_src)) {
        $img = $a_img_src[0];
      }
    }
  }
  else if ( is_singular() && has_post_thumbnail() ) {
    $img = get_the_post_thumbnail_url($post, 'og_image');
  }

  $a["og:image"] = $img;

  if ( $_queried_object && "WP_Term" == get_class($_queried_object)) {
    $a["og:url"] = get_term_link($_queried_object);
  }
  else if ( is_home() || is_front_page() ) {
    $a["og:url"] = get_option('home');
  }
  else if ( $post && "WP_Post" == get_class( $post) ) {
    $a["og:url"] = get_the_permalink($post);
  }

  $a["og:title"] = get_bloginfo( 'name' );

  if ( is_archive() ) {
    $a["og:title"] = $_queried_object->name;
  } else if ( is_singular() ) {
    $a["og:title"] = get_the_title();
  }

  $r = '';

  foreach ($a as $prop => $content) {
    $r .= '<meta property="' . $prop . '" content="' . $content . '">';
    $r .= "\n";
  }

  return $r;
}

/**
 * ACF settings exported as PHP code.
 */
require_once(__DIR__ . '/inc/acf.php');